
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE INVITE CASCADE CONSTRAINTS;
DROP TABLE CPOST CASCADE CONSTRAINTS;
DROP TABLE ADDON CASCADE CONSTRAINTS; 
DROP TABLE ADDTAG CASCADE CONSTRAINTS; 
DROP TABLE HASHTAG CASCADE CONSTRAINTS; 


CREATE TABLE MEMBER(
    UCODE VARCHAR2(20) PRIMARY KEY,
    UEMAIL VARCHAR2(100) NOT NULL,
    UPWD VARCHAR2(60),
    UNAME VARCHAR2(30) NOT NULL,
    UPHONE NUMBER,
    NUM VARCHAR2(20),
    UGROUP VARCHAR2(100),
    UROLE VARCHAR2(100),
    AUTHST VARCHAR2(1) DEFAULT 'N' NOT NULL CHECK (AUTHST IN('Y', 'N')),
    UDATE DATE DEFAULT SYSDATE,
    SIGNTYPE VARCHAR2(30) CHECK (SIGNTYPE IN('hwabo', 'googel', 'naver')),
    ACCESSTOKEN VARCHAR2(100),
    UIMG VARCHAR2(255)
);

COMMENT ON COLUMN MEMBER.UCODE IS '사용자번호';
COMMENT ON COLUMN MEMBER.UEMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.UPWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.UNAME IS '이름';
COMMENT ON COLUMN MEMBER.UPHONE IS '핸드폰';
COMMENT ON COLUMN MEMBER.NUM IS '소속된 프로젝트 번호';
COMMENT ON COLUMN MEMBER.UGROUP IS '소속';
COMMENT ON COLUMN MEMBER.UROLE IS '역할';
COMMENT ON COLUMN MEMBER.AUTHST IS '이메일 인증여부';
COMMENT ON COLUMN MEMBER.UDATE IS '사용자 등록일자';
COMMENT ON COLUMN MEMBER.SIGNTYPE IS '회원가입 타입';
COMMENT ON COLUMN MEMBER.ACCESSTOKEN IS '인증키(sns가입자)';
COMMENT ON COLUMN MEMBER.UIMG IS '내 정보 이미지';

CREATE TABLE INVITE(
    INVTKEY VARCHAR2(60) PRIMARY KEY,
    UCODE VARCHAR2(20),
    NUM VARCHAR2(20) NOT NULL,
    INVTEMAIL VARCHAR2(100) NOT NULL,
    INVTUSE VARCHAR2(30) NOT NULL, CHECK(INVTUSE IN ('Y','N')),
    EXPRTDATE DATE DEFAULT (SYSDATE+1)
);

COMMENT ON COLUMN invite.INVTKEY IS '초대장 식별키';
COMMENT ON COLUMN invite.UCODE IS '초대를 보낸 사용자 번호';
COMMENT ON COLUMN invite.NUM IS '초대한 프로젝트 번호';
COMMENT ON COLUMN invite.INVTEMAIL IS '초대를 받는 이메일 주소';
COMMENT ON COLUMN invite.INVTUSE IS '초대장 사용여부';
COMMENT ON COLUMN invite.EXPRTDATE IS '만료일';

CREATE TABLE CPOST(
    NO VARCHAR2(50) PRIMARY KEY,
    TITLE VARCHAR2(100),
    WRITER VARCHAR2(30) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    ENROLLDATE DATE DEFAULT SYSDATE,
    OPEN VARCHAR2(1) CHECK(OPEN IN ('Y','N')),
    LOVE NUMBER DEFAULT 0,
    HASHTAGS VARCHAR2(100),
    MENTIONS VARCHAR2(100),
    RWRITER VARCHAR2(30),
    RCONTENT VARCHAR2(500),
    ADDONUSE VARCHAR2(1) CHECK(ADDONUSE IN ('Y','N'))
);

COMMENT ON COLUMN cpost.NO IS '번호';
COMMENT ON COLUMN cpost.TITLE IS '제목';
COMMENT ON COLUMN cpost.WRITER IS '작성자';
COMMENT ON COLUMN cpost.CONTENT IS '내용';
COMMENT ON COLUMN cpost.ENROLLDATE IS '등록일';
COMMENT ON COLUMN cpost.OPEN IS '공개여부';
COMMENT ON COLUMN cpost.LOVE IS '좋아요 수';
COMMENT ON COLUMN cpost.HASHTAGS IS '해시태그';
COMMENT ON COLUMN cpost.MENTIONS IS '멘션';
COMMENT ON COLUMN cpost.RWRITER IS '댓글작성자';
COMMENT ON COLUMN cpost.RCONTENT IS '댓글내용';
COMMENT ON COLUMN cpost.ADDONUSE IS '애드온 사용여부';

CREATE TABLE ADDON(
    NO VARCHAR2(50) NOT NULL,
    LOCALNO VARCHAR2(10),
    MAPX VARCHAR2(10),
    MAPY VARCHAR2(10),
    OFILE1 VARCHAR2(100),
    RFILE1 VARCHAR2(100),
    OFILE2 VARCHAR2(100),
    RFILE2 VARCHAR2(100),
    OFILE3 VARCHAR2(100),
    RFILE3 VARCHAR2(100)
);

COMMENT ON COLUMN addon.NO IS '게시글 번호';
COMMENT ON COLUMN addon.LOCALNO IS '지도 요청url';
COMMENT ON COLUMN addon.MAPX IS '지도 x좌표';
COMMENT ON COLUMN addon.MAPY IS '지도 y좌표';
COMMENT ON COLUMN addon.OFILE1 IS '원본파일명';
COMMENT ON COLUMN addon.RFILE1 IS '서버저장파일명';
COMMENT ON COLUMN addon.OFILE2 IS '원본파일명';
COMMENT ON COLUMN addon.RFILE2 IS '서버저장파일명';

CREATE TABLE ADDTAG(
    NO VARCHAR2(30),
    TAGID VARCHAR2(100)
);

COMMENT ON COLUMN addtag.NO IS '태그한 게시글 번호';
COMMENT ON COLUMN addtag.TAGID IS '태그 아이디';

CREATE TABLE HASHTAG(
    TAGID VARCHAR2(100) PRIMARY KEY,
    TAGNAME VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN hashtag.TAGID IS '태그 아이디';
COMMENT ON COLUMN hashtag.TAGNAME IS '태그명';

ALTER TABLE INVITE
ADD CONSTRAINT FK_UCODE_MEMBER 
FOREIGN KEY (UCODE) 
REFERENCES MEMBER(UCODE)
ON DELETE CASCADE;

ALTER TABLE INVITE
ADD CONSTRAINT FK_NUM_PROJECT
FOREIGN KEY (NUM) 
REFERENCES PROJECT(NUM)
ON DELETE CASCADE;

ALTER TABLE CPOST
ADD CONSTRAINT FK_WRITER_MEMBER 
FOREIGN KEY (WRITER) 
REFERENCES MEMBER(UCODE)
ON DELETE CASCADE;

ALTER TABLE ADDON
ADD CONSTRAINT FK_ADD_NO_CPOST
FOREIGN KEY (NO) 
REFERENCES CPOST(NO)
ON DELETE CASCADE;

ALTER TABLE ADDTAG
ADD CONSTRAINT FK_NO_CPOST
FOREIGN KEY (NO) 
REFERENCES CPOST(NO)
ON DELETE CASCADE;

ALTER TABLE ADDTAG
ADD CONSTRAINT FK_TAGID_HASHTAG
FOREIGN KEY (TAGID) 
REFERENCES HASHTAG(TAGID)
ON DELETE CASCADE;

COMMIT;
